Here it is...
  2%|████                                                                                                                                                              | 5/200 [05:40<3:41:20, 68.11s/it]
Traceback (most recent call last):
  File "/home/user/georgy/Zett/zett/train.py", line 1610, in <module>
    main()
  File "/home/user/georgy/Zett/zett/train.py", line 1511, in main
    state, train_metric = current_step_fn(state, batch)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 83843772824 bytes.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
